[package]
name = 'rustyphylotyper'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'rustyphylotyper'

[dependencies]
anyhow = "1.0.81"
bitvector = "0.1.5"
extendr-api = { version = "0.6.0", features = ["ndarray"] }
ndarray = "0.15.6"
