# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rustyphylotyper_wrappers", use_symbols = TRUE, package_name = "rustyphylotyper")

#' @docType package
#' @usage NULL
#' @useDynLib rustyphylotyper, .registration = TRUE
NULL

#' Construct k-mer database
#' @export
kmer_database <- function(sequences, genera, kmer_size) .Call(wrap__kmer_database, sequences, genera, kmer_size)


# nolint end
