# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rustyphylotyper_wrappers", use_symbols = TRUE, package_name = "rustyphylotyper")

#' @docType package
#' @usage NULL
#' @useDynLib rustyphylotyper, .registration = TRUE
NULL

#' Temporary function that returns the indexes (in base4) of the kemers.
#' @export
kmers <- function(sequence, k) .Call(wrap__kmers, sequence, k)


# nolint end
